version = 0.1
[default.deploy.parameters]
stack_name = "safeguard-backend"
resolve_s3 = true
s3_prefix = "safeguard-backend"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
