AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Safeguard Backend API

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  SafeguardBackend:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.safeguard.safeguardbackend.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 2048
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Timeout: 60
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '1.0'

Outputs:
  SpringBootPetStoreApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/product'
    Export:
      Name: SpringBootPetStoreApi