AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Safeguard Backend API

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    Cors:
      AllowMethods: "'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  SafeguardBackendApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyCognitoAuth
        Authorizers:
          MyCognitoAuth:
            Type: COGNITO_USER_POOLS
            UserPoolArn: "CognitoUserPoolARN"
  SafeguardBackend:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.safeguard.safeguardbackend.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 2048
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Timeout: 60
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref SafeguardBackendApi
            Auth:
              Authorizer: MyCognitoAuth
